"""remove output_path from evaluate info table

Revision ID: 47bad052a525
Revises: a9e9e64a22fc
Create Date: 2025-04-02 06:52:06.478365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bad052a525'
down_revision = 'a9e9e64a22fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluate_info', schema=None) as batch_op:
        batch_op.drop_column('output_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluate_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_path', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
