"""initial migration

Revision ID: a9e9e64a22fc
Revises: 
Create Date: 2025-04-02 05:54:43.875187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e9e64a22fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_info',
    sa.Column('uuid', sa.String(length=37), nullable=False),
    sa.Column('dataset_type', sa.Integer(), nullable=False, comment='数据集类型(1-3)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='类别'),
    sa.Column('scenario', sa.String(length=50), nullable=False, comment='场景'),
    sa.Column('location', sa.String(length=100), nullable=False, comment='地点'),
    sa.Column('center_frequency', sa.String(length=50), nullable=False, comment='中心频率'),
    sa.Column('bandwidth', sa.String(length=50), nullable=False, comment='带宽'),
    sa.Column('data_group_count', sa.String(length=50), nullable=False, comment='数据组数'),
    sa.Column('applicable_models', sa.Text(), nullable=False, comment='适用模型，多个模型用英文逗号分隔'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('model_info',
    sa.Column('uuid', sa.String(length=37), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='模型任务(1-4)'),
    sa.Column('output_type', sa.String(length=100), nullable=False, comment='模型输出'),
    sa.Column('model_category', sa.String(length=50), nullable=False, comment='模型类别'),
    sa.Column('application_scenario', sa.String(length=50), nullable=False, comment='应用场景'),
    sa.Column('test_data_count', sa.Integer(), nullable=False, comment='测试数据数量'),
    sa.Column('training_date', sa.DateTime(), nullable=False, comment='模型训练日期'),
    sa.Column('parameter_count', sa.String(length=50), nullable=False, comment='模型参数量'),
    sa.Column('convergence_time', sa.String(length=50), nullable=False, comment='模型收敛时长'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('dataset_detail',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('dataset_uuid', sa.String(length=37), nullable=False, comment='关联的数据集UUID'),
    sa.Column('description', sa.Text(), nullable=False, comment='数据介绍'),
    sa.Column('detail_json', sa.Text(), nullable=False, comment='详细信息，JSON格式存储'),
    sa.Column('picture1_path', sa.String(length=255), nullable=True, comment='图片1路径'),
    sa.Column('picture2_path', sa.String(length=255), nullable=True, comment='图片2路径'),
    sa.Column('input_path', sa.String(length=255), nullable=True, comment='输入文件夹路径'),
    sa.ForeignKeyConstraint(['dataset_uuid'], ['dataset_info.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('dataset_uuid')
    )
    op.create_table('evaluate_info',
    sa.Column('uuid', sa.String(length=37), nullable=False),
    sa.Column('evaluate_type', sa.Integer(), nullable=False, comment='验证任务类型(1-4)'),
    sa.Column('model_uuid', sa.String(length=37), nullable=True, comment='关联的模型UUID'),
    sa.Column('dataset_uuid', sa.String(length=37), nullable=True, comment='关联的数据集UUID'),
    sa.Column('evaluate_status', sa.String(length=20), nullable=False, comment='验证任务状态'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='任务开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='任务结束时间'),
    sa.Column('extra_parameter', sa.Text(), nullable=True, comment='额外参数'),
    sa.Column('output_path', sa.String(length=255), nullable=True, comment='输出目录路径'),
    sa.ForeignKeyConstraint(['dataset_uuid'], ['dataset_info.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_uuid'], ['model_info.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('model_detail',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('model_uuid', sa.String(length=37), nullable=False, comment='关联的模型UUID'),
    sa.Column('description', sa.Text(), nullable=False, comment='模型简介'),
    sa.Column('architecture_image_path', sa.String(length=255), nullable=True, comment='模型架构图片路径'),
    sa.Column('architecture_text', sa.Text(), nullable=False, comment='模型架构文本'),
    sa.Column('feature_design_image_path', sa.String(length=255), nullable=True, comment='模型特征设计图片路径'),
    sa.Column('feature_design_text', sa.Text(), nullable=False, comment='模型特征设计文本'),
    sa.Column('code_file_path', sa.String(length=255), nullable=True, comment='模型代码文件路径'),
    sa.Column('env_file_path', sa.String(length=255), nullable=True, comment='模型环境文件路径'),
    sa.ForeignKeyConstraint(['model_uuid'], ['model_info.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('model_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_detail')
    op.drop_table('evaluate_info')
    op.drop_table('dataset_detail')
    op.drop_table('model_info')
    op.drop_table('dataset_info')
    # ### end Alembic commands ###
